#+TITLE: Unit 2 - Knowledge Representation: Object Oriented Representation

* Exercise 33

Provide a system of Frames to represent all the following assertions

** A library is a place where there are books, magazines, CDs, and DVDs
** All books are written by one or several authors that are men or women
** There are some books that are anonymous
** Library books, magazines, CDs, and DVDs can be borrowed by library members, which are men or women
** The books with arrival date the current year cannot be borrowed

* Exercise 34

Provide a system of Frames to represent all the following assertions

** Planes land and take off in airports
** All planes belong to a Flight Company
** Flight Companies may organize into Alliances
** Star Alliance is an alliance that contains the Flight Companies Air Canada, Spanair, Air China, Thai, and others
** Planes flight from one airport to another following a timetable
** There are two sorts of flight tickets: tourist, and business

* Exercise 35

Represent with OO knowledge representation (frames and COOL) the following knowledge base

** Vehicles are means of transportation with wheels with many possible colors and there are companies building different models of vehicles
** There are vehicles that are classic-cars. These cars are made by a company
** All classic-cars must have a company (i.e., company slot of CLASSIC-CAR is not optional)
** Classic-cars have a model. If the company making the car doesn’t have this model in its list of models, it is inserted
** Classic-cars have a factory price (the cost of producing the car) and a retail price (the cost to final client). Retail price is always 30% more than the factory-price, and the factory-price can change the production costs
** Classic-cars have a horsepower value that must be always in the range [50, 200]
** Classic-cars have one single color that can be red, white, black, yellow, dark, or other. The information is stored codified, and recovered decodified
** Persons can buy and sell classic-cars with the corresponding exchange of money

* Exercise 36

For the following domains:

- Classroom scheduler :: Build a program that helps schedule rooms for classes of various sizes at a university, using the sort of frame technology (frames, slots, and facets). Slots of frames might be used to record when and where a class is to be held, the capacity of a room, etc., and IF-ADDED and other facets might be used to encode constraints as well as to fill in implied values when the KB is updated. In this exercise, we want to consider updating the KB in several ways: (1) asserting that a class of a given size is to be held in a given room at a given time; the system would either go ahead and add this to its schedule, or alert the user that it was not possible to do so; (2) asserting that a class of a given size is to be held at a given time, with the system providing a suitable room (if one is available) when queried; (3) asserting that a class of a given size is desired, with the system providing a time and place when queried.
- Olympic assistant :: We want to help the International Olympic Committee in the smooth running of the next Olympic Games. In particular, we want to select an event and write a program to deal with that event including facilities for handling the preliminary rounds/heats and finals. Slots of frames might be used to record athletes in a heat/final, the location and time of that heat/final, etc. and IF-ADDED/IF-NEEDED and other procedures might be used to encode constraints as well as fill in implied values when the knowledge base is updated. We particularly wish to consider several ways of updating the knowledge base: (1) asserting that a heat will take place with certain athletes. The system should add this and determine what time and the location of the venue the athletes need to be at for their heat, etc; (2) asserting that a particular semi-final/final should take place, the system should determine the participating athletes; and, (3) asserting that the medal ceremony should take place at a particular time and location, the system should add this and provide the medalists plus appropriate national anthem when queried. To simplify matters, we assume that an athlete takes part in only the event we have chosen.

** Design a set of frames and slots to represent the schedule and any ancillary information needed by the assistant
** For  all  slots  of  all  frames,  write  in  pseudo-code  the  IF-ADDED  or  IF-NEEDED  procedures  that  would  appear  there.  Annotate  these  procedures  with  comments  explaining why they are there (e.g., what constraints they are enforcing)
** Briefly explain how your system would work (what procedures would fire and what they would do) on concrete examples of your choosing illustrating each of the three situations (1, 2, and 3) mentioned in the application

* Exercise 37

Provide a frame system for exercise a)

* Exercise 38

Provide a frame system for exercise a)

* Exercise 39

Provide a Script to represent the process of borrowing a book in a Library that could cover the following steps: enter into the library, look for a book in the shelves, in the computer, or directly with the librarian, make the reservation, go home with the book (if it was found), and return the book after some time.

* Exercise 40

Provide a Script to represent the process of flying (direct flights) between two airports: find all the companies that connect these airports, then ask for the time tables, select one sort of ticket, and purchase the ticket.

* Exercise 41

In a company there are three departments: Production, Sells, and Marketing. All the departments have one head which is a person with university studies, and other employees that are the workers. All workers of the Production department have a work turn of morning, afternoon, or over-night, and the turn of one person cannot be changed if the number of workers in the leaving turn goes below 10. The company produces two sorts of products: intermediate and final. Intermediate products remain in the Production department as components to produce other more complex products. Final products are those that are ready to be commercialized. All sorts of products have a production rate in units per hour. Once the final products are produced they are added to the catalog of available products. Clients made requests of the sort (n, p) where n is the number of units requested of product p. The workers of the Sell department solve the requests with products in the catalog of available products. Workers in the Marketing department analyze the catalog of available products to detect whether there many products of each sort (each product has an indicator of overstocked) and start a commercial campaign to sell these products to the company clients. The amount of work between workers of the same department are tried to keep balanced: all production workers are assigned one turn, the accumulated number of requests attended for the sellers is +/-1 the same, and number of campaigns triggered by each marketing worker is +/-1 the same.

** Provide a frame system to represent this domain
** Provide a script system to describe the production-marketing-selling procedure

* Exercise 42

Represent with Frames the following knowledge: “An agenda is a list of meeting activities in the order in which they are to be taken up. Meeting activities can be professional and personal, and all of them have a priority. They have a date, duration in hours, and place. Optionally they may also have a person to which the meeting is been held with. When a meeting activity is introduced in the agenda it may create a conflict with a previous meeting and if the new meeting is more priority, the previous one is shifted to a list of to-be-assigned activities of the agenda.

We consider that all the meeting activities are held, except those in the to-be-assigned list. The agenda also has an activity ratio which indicates the proportion of hours that the owner of the agenda has been met with respect to all the activities registered in the agenda (including the ones in the to-be-assigned list).”

* Exercise 43

Represent with Frames the following knowledge: “Backyards in houses are leisure surfaces with an extension measured in m2 containing elements such as vegetal, sport elements and constructions. Vegetal elements can be of the sort trees, bushes, and grass. Each one having a Latin and an ordinary name, a need of water measured in litters per day, a cost (which is unitary for trees and brushes, but which is per m2 for grass). Moreover, they occupy a surface in m2. Sport elements are swimming pools, and tennis courts. Both have extensions in m2, but swimming pools require refilling of water in terms of litters per day. Both elements have a construction cost. Finally, backyard constructions can be huts and greenhouses. Both of them occupy a surface in m2, and have a construction cost. Greenhouses require a supply of water in litters per day. The surface of the grass in a backyard is usually computed as the difference between the whole backyard and the rest of elements in the backyard. The need of water (and the cost) of the backyard is computed as the addition of the needs of water (and costs) of all the elements contained.”
