#+TITLE: Unit 2 - Knowledge Representation: Network Representation

* Exercise 44

Provide a definitional semantic network representing the knowledge in the following paragraph: “Mammals (class Mammalia) are a class of vertebrate animals characterized by the presence of sweat glands, including sweat glands modified for milk production, hair, three middle ear bones used in hearing, and a neocortex region in the brain. All mammals (except for the five species of monotremes) give birth to live young instead of laying eggs. Most mammals also possess specialized teeth, and the largest group of mammals, the placentals, uses a placenta during gestation”

* Exercise 45

.Provide a definitional semantic network representing the knowledge in the following paragraph: “A rocket or rocket vehicle is a missile, aircraft or other vehicle which obtains thrust by the reaction of the rocket to the ejection of fast moving fluid from a rocket engine. Chemical rockets work by the action of hot gas produced by the combustion of the propellant  against  the  inside  of  combustion  chambers  and  expansion  nozzles.  This  generates forces that accelerate the gas to extremely high speed and exert a large thrust on the rocket”.

* Exercise 46

Provide an assertional semantic network to represent the following knowledge: “People are mammals. Rockets can be crewed or not. All the crewed rockets are crowed by people. All the rockets lift-off, but not all of them land. Outspace rockets are crewed by astronauts. If an outspace rocket lands, the astronaut becomes a hero. Neil Armstrong and Yuri Gagarin were astronauts of Gemini 8 and Vostok 1 rockets, respectively”.

* Exercise 47

Make a Petri Net to pipeline the following process of making bread: “Get the ingredients: yeast (2 Tbsp.), hot-ish water (2 cups), bread flour (5 cups total, 2 for the sponge and 3 for later.), sugar (2 Tbsp.), salt (2 tsp.), and oil (2 Tbsp.). Make the sponge: start by mixing 2 cups of hot-ish water and the flour, then add 2 Tbsp. sugar, 2 Tbsp. oil, 2 Tbsp. yeast, and 2 tsp. salt. Add some flour and knead it: add ''about'' 3 more cups of flour. Let it rise in a warm 14 place for about 45 minutes to an hour, it should be about doubled in size by the time it's finished. Put it in the loaf pans: punch the dough down and divide it into 3 parts. Spray the pans and put the dough in. Let it rise again in the pans. Bake it: preheat your oven to 350 degrees and put the loaves in. Bake them for about 25 minutes. Your quick read thermometer should read between 180 and 190 degrees. Pull the loaf”.

* Exercise 48

Construct a definitional semantic network to represent the world of airlines: “Airlines have planes and hire pilots and hostesses that are assigned to planes; planes are assigned to flights; flights are between two cities (from and to), they have two dates and hours assigned (departure and arrival); flights define travels, though travels can have several flights connected; passengers are assigned to travels; cities have an intended influence population that can be high, medium or low; flights between two high populated cities require big planes; flights between two low populated cities require small planes; the rest of flights require medium planes.”

* Exercise 49

Construct a definitional semantic network to represent the world of chairs: “A chair is a piece of furniture with a raised surface used to sit on, commonly for use by one person. Chairs are most often supported by four legs and have a back; however, a chair can have three legs or could have a different shape. A chair without a back or arm rests is a stool, or when raised up, a bar stool. A chair with arms is an armchair and with folding action and reclining footrest, a recliner. A permanently fixed chair in a train or theater is a seat or, in an airplane, airline seat; when riding, it is a saddle and bicycle saddle, and for an automobile, a car seat or infant car seat. With wheels it is a wheelchair and when hung from above, a swing.” (Extracted from Wikipedia)
