#+TITLE: Unit 1 - Introduction and Concepts

* What is the difference between data, information and knowledge?

These terms are used to describe closely related concepts. This is also the reason why they are often, and sometimes improperly, interchanged.

*Data* itself is a values collection of qualitative or quantitative variables that are measured, collected, reported and analyzed. It may encode some information or knowledge. Data can be raw or unprocessed, adjectives implying that data requires further processing before being used. In its rawest form, data can be seen as a stone dug from a mine: a certain, intentional effort has been made to take it from where it was with the hope to gain something from it.

*Information* is strictly related to the concept of uncertainty: to break uncertainty we need information. To store or transmit it, we use data. Information is extracted from (raw) data as a result of a processing, which may contextualize, categorize, calculate, correct and/or condensate the input data. Compared to raw data, information may be seen as a gemstone that has undergone several processes to increase its value.

*Knowledge* takes information to a higher level of abstraction: the objective here is understanding. If information may describe a context, knowledge aims to extend its uncertainty-breaking power to other contexts. Compared to information, knowledge may be seen as a jewel: its true value is appreciated when used in the right situations.

* Identify data, information and know-what/know-how knowledge

About the following exercises
- Exercises 2 and 3 are grouped together for convenience
- The paragraphs are already splitted into separate sentences for the same reason
- We adopt these conventions: _this is an information_, ~this is a value~ and /this is its meaning/
  + Knowledge :: extracted from the sentence above
  + Know-what :: if the extracted knowledge concerns factual assertions
  + Know-how :: if the extracted knowledge concerns procedures

** 2a and 3a

 1) This course of _~Knowledge Representation and Engineering~ /course name/_ is composed of _~three~ /number of/ chapters_:  _~Introduction  and  Concepts~ /chapter name/_, _~Knowledge  Representation~ /chapter name/_, and _~Knowledge Engineering~ /chapter name/_.
    + Knowledge :: Knowledge Representation and Engineering is a course
    + Knowledge :: Knowledge Representation and Engineering is composed by three chapters
    + Knowledge :: Introduction and Concepts is a chapter of Knowledge Representation and Engineering
    + Knowledge :: Knowledge Representation Knowledge Representation and Engineering
    + Knowledge :: Knowledge Engineering chapter Knowledge Representation and Engineering
    + Know-what :: it's a fact
 2) It’s a _~six-credit~ /number of/ course_ with _~two~ week /number of/ hours_ for _~theory~ /type of class/_ and _~two~ /number of/ week hours_ for _~problems and practice~ /type of class/_.
    + Knowledge :: Knowledge Representation and Engineering is a six-credit course
    + Knowledge :: Knowledge Representation and Engineering has two week hours for theory
    + Knowledge :: Knowledge Representation and Engineering has two week hours for problems and practice
    + Know-what :: it's a fact
 3) Like all the other subjects in the _~master~ /host of the course/_, _~half~ /amount/ of the practical hours_ will be off class.
    + Knowledge :: Knowledge Representation and Engineering is a subject of the master
    + Knowledge :: All the subjects in the master have half of the practical hours off class
    + Know-how :: it's a fact
 4) As the rest of subjects, KRE will be _~continuously evaluated~ /type of evaluation/_.
    + Knowledge :: All the subjects in the master are continuously evaluated
    + Know-what :: it's a fact
 5) Continuous evaluation in KRE will consist of _~two~ /amount of/ theoretical-practical tests_, and _~two~ /amount of/ practical work deliveries_.
    + Knowledge :: the continuous evaluation of Knowledge Representation and Engineering consists of two theoretical-practical tests, and two practical work deliveries
    + Know-what :: it's a fact
 6) The final mark will be calculated as _~30%~ /amount/ of the results of each one of the theoretical tests_ and _~20%~ /amount/ of each practical work /means of evaluation/_.
    + Knowledge :: the final mark of Knowledge Representation and Engineering is 30% of the results of each one of the theoretical tests and 20% amount of each practical work
    + Know-how :: it's a procedure describing how the final mark is calculated
 7) For second evaluation, there will be a _~single exam~ /means of evaluation/_.
    + Knowledge :: the second evaluation of Knowledge Representation and Engineering is a single exam
    + Know-what :: it's a fact

** 2b and 3b

 1) _~Computer hardware~ /part/_ equals the collection of _~physical elements~ /type of/_ that comprise a computer system.
    + Knowledge :: computer hardware is the collection of physical elements that comprise a computer system
    + Know-what :: it's a fact
 2) Computer hardware refers to the _~physical parts or components~ /type of/_ of a computer such as _~monitor~ /part name/_, _~keyboard~ /part name/_, _~hard drive disk~ /component name/_, _~mouse~ /part name/_, _~printers~ /part name/_, _~graphic cards~ /component/_, _~sound cards~ /component name/_, _memory /component name/_, _motherboard /component name/_ and _chips /component name/_, etc. all of which are _~physical objects~ /type of object/_ that you can actually touch.
    + Knowledge :: computer hardware is a collection of physical elements that are parts or components of a computer system
    + Knowledge :: monitor, hard drive disk, mouse, printers, graphic cards, sound cards, memory, motherboard, chips are part of computer hardware
    + Knowledge :: monitor, hard drive disk, mouse, printers, graphic cards, sound cards, memory, motherboard, chips are physical objects
    + Know-what :: it's a fact
 3) In contrast, _~software~ /part/_ is untouchable.
    + Knowledge :: software is untouchable
    + Know-what :: it's a fact
 4) Software exists as _~ideas~ /part of/_, _~application~ /part of/_, _~concepts~ /part of/_, and _~symbols~ /part of/_, but it has _~no substance~ /property of software/_.
    + Knowledge :: software is made of ideas, application, concepts and symbols
    + Knowledge :: software has no substance
    + Know-what :: it's a fact
 5) A combination of _~hardware~ /part/_ and _~software~ /part/_ forms a usable computing system.
    + Knowledge :: a usable computing system is made by hardware and software
    + Know-what :: it's a fact

** 2c and 3c

 1) Primary care is the _~health care~ /type of care/_ given by a _~health care provider~ /role/_.
    + Knowledge :: primary care is health care
    + Knowlegde :: health care provider provides primary care
    + Know-what :: it's a fact
 2) Typically this provider acts as the _~principal point of consultation~ /level of consultation/_ for _~patients~ /role/_ within a health care system and coordinates other _~specialists~ /role/_ that the patient may need.
    + Knowledge :: health care provider is the principal consultant for patients
    + Knowledge :: health care provider coordinates other specialists
    + Know-what :: it's a fact
 3) Such a professional can be a _~primary care physician~ /role/_, such as a _~general practitioner~ /role/_ or _~family physician~ /role/_, or depending on the locality, health system organization, and patient's discretion, they may see a _~pharmacist~ /role/_, a _~physician assistant~ /role/_, a _~nurse practitioner~ /role/_, a _~nurse~ /role/_ (such as in the _~United Kingdom~ /location_)/, a _~clinical officer~ /role/_ (such as in _~parts of Africa~ /location/_), or an _~Ayurvedic or other traditional medicine professional~ /role/_ (such as in _~parts of Asia~ /location/_).
    + Knowledge :: primary care physician can be a health care provider
    + Knowledge :: general practitioner is a primary care physician
    + Knowledge :: family physician is a primary care physician
    + Knowledge :: pharmacist can be a health care provider
    + Knowledge :: physician assistant can be a health care provider
    + Knowledge :: nurse practitioner can be a health care provider
    + Knowledge :: nurse can be a health care provider in United Kingdom
    + Knowledge :: clinical officer can be a health care provider in parts of Africa
    + Knowledge :: traditional medicine professional can be a health care provider in parts of Asia
    + Know-how :: it's a procedure describing how a primary care physician is chosen
 4) A _~patient-centered primary care~ /type of/_ stores all the information about one patient in the different _~episodes of care (eoc)~ /storing format/_.
    + Knowledge :: patient-centered primary care stores all the information about one patient in the different episodes of care (eoc)
    + Know-what :: it's a fact
 5) A _patient /role/_ has a _~name~, ~sex~ (M or W), ~race~, and a ~date of birth~ /attributes of a patient/_.
    + Knowledge :: name, sex, race and date of birth are attributes of a patient
    + Know-what :: it's a fact
 6) An eoc contains the _~date when episode was created~, and a ~sequence of encounters~ /attribute of an eoc/_ between the health care professional and the patient.
    + Knowledge :: date of creation and sequence of encounters with patient are attributes of a eoc
    + Know-what :: it's a fact
 7) Each encounter has a _~date~ a ~reference to the health care provider~ and a ~set of treatments~ /attributes of an encounter/_.
    + Knowledge :: date, reference to health care provider, set of treatments are attributes of an encounter
    + Know-what :: it's a fact
 8) A treatment is composed of a _~set of findings~ /part of treatment/_ which are _~textual~ /type of/ descriptions_ of the patient signs and symptoms (for example, _~fever~, ~high blood pressure~, ~breast pain~, /symptoms/_ ...).
    + Knowledge :: treatment has a set of findings
    + Knowledge :: set of findings collects textual descriptions of signs and symptoms
    + Knowledge :: fever, high blood pressure, breast pain are symptoms
    + Know-what :: its' a fact
 9) A treatment can have attached a _~disease or set of diseases~ /attribute of a treatment/_ that the patient is treated of, and a set of _~medical actions~ /attribute of a treatment/_ that can be of the sort: _~pharmacological~, ~test order~, ~visit~ (to provider such as a specialist), or ~recommendation~ /type of medical actions/_.
    + Knowledge :: treatment may have a set of diseases that the patient is treated of
    + Knowledge :: treatment may have a set of medical actions
    + Knowledge :: medical action can be pharmacological, test order, visit (to a specialist), or recommendation.
    + Know-what :: it's a fact

** 2d and 3d

 1) A chair is a _~raised surface~ /type of surface/_ used to sit on, commonly for use by _~one~ /number of/ person_.
    + Knowledge :: chair is a raised surface used to sit on
    + Knowledge :: chair is commonly used by one person at a time
    + Know-what :: it's a fact
 2) Chairs are most often supported by _~four~ /number of/ legs_ and have a back; however, a chair can have _~three~ /number of/ legs_ or could have a _~different /type of/ shape~_.
    + Knowledge :: chair is often supported by four legs and have a back
    + Knowledge :: chair can vary in shape and number of legs
    + Know-what :: it's a fact
 3) A chair without a back or arm rests is a _~stool~ /type of chair/_, or when raised up, a _~bar stool~ /type of chair/_.
    + Knowledge :: stool is a chair without a back
    + Knowledge :: bar stool is a raised up stool
    + Know-what :: it's a fact
 4) A chair with arms is an _~armchair~ /type of chair/_ and with folding action and inclining footrest, a _~recliner~ /type of chair/_.
    + Knowledge :: amrchair is a chair with arms
    + Knowledge :: recliner is an armchair with folding action and inclining footrest
    + Know-what :: it's a fact
 5) A permanently fixed chair in a train or theater is a _~seat~ /type of chair/_ or, in an airplane, _airline seat~ /type of chair/_; when riding, it is a _~saddle~ /type of chair/_ and _~bicycle saddle~ /type of chair/_, and for an automobile, a _~car seat~ /type of chair/_ or _~infant car seat~ /type of chair/_.
    + Knowledge :: seat is a permanently fixed chair
    + Knowledge :: airline seat is a seat in an airplane
    + Knowledge :: saddle is a seat used to ride
    + Knowledge :: bicycle saddle is a saddle for a bike
    + Knowledge :: car seat is a seat in a car
    + Knowledge :: infant car sear is a seat in a car
    + Knowledge-what :: it's a fact, describing specific nomenclature for different scenarios
    + Knowledge-how :: it also can be seen as procedure describing the naming logic for some of the scenarios
 6) With wheels it is a _~wheelchair~ /type of chair/_ and when hung from above, a _~swing~ /type of chair/_.
    + Knowledge :: wheelchair is a chair with wheels
    + Knowledge :: swing is a hung chair
    + Know-what :: it's a fact

** 2e and 3e

1) The Nobel Prizes are _~annual~ /frequency/_ _~international~ /scope/_ awards bestowed by _~Scandinavian committees~ /awarder/_ in recognition of _~cultural and scientific advances~ /type of achievement/_.
   + Knowledge :: nobel prizes are awards
   + Knowledge :: nobel prizes are annual
   + Knowledge :: nobel prizes are international
   + Knowledge :: nobel prizes are awarded by Scandinavian commitees
   + Knowledge :: nobel prizes are awarded for cultural and scientific advances
   + Know-what :: it's a fact
2) The will of the _~Swedish~ /nationality/_ _~chemist~ /qualification/_ _~Alfred Nobel~ /name/_, the _~inventor of dynamite~ /achievement/_, established the prizes in _~1895~ /year/_.
   + Knowledge :: Alfred Nobel is swedish
   + Knowledge :: Alfred Nobel is a chemist
   + Knowledge :: Alfred Nobel is the inventor of dynamite
   + Knowledge :: Alfred Nobel established the nobel prizes in 1895
   + Know-what :: it's a fact
3) The _~2~ /number of/ prizes_ in _~Physics~, ~Chemistry~, ~Physiology or Medicine~, ~Literature~, and ~Peace~ /type of field/_ were first awarded in _~1901~_.
   + Knowledge :: Physics, Chemistry, Physiology or Medicine, Literature, and Peace are nobel prizes
   + Knowledge :: Physics had 2 nobel prizes in 1901
   + Know-fact :: it's a fact
4) The Peace Prize is awarded in _~Oslo, Norway~ /location/_, while the other prizes are awarded in _~Stockholm, Sweden~ /location/_.
   + Knowledge :: Peace prize is awarded in Oslo, Norway
   + Knowledge :: Physics, Chemistry, Physiology or Medicine, Literature are awarded in Stockholm, Sweden
   + Know-what :: it's a fact
5) Each Nobel Prize is regarded as the _~most prestigious~ /level of recognition of/ award_ in its field.
   + Knowledge :: nobel prizes are the most prestigious award in their field
   + Know-what :: it's a fact
6) In 1968, _~Sveriges Riksbank~ /name/_ instituted an award that is often associated with the Nobel prizes, the _~Sveriges Riksbank Prize in Economic Sciences in Memory of Alfred Nobel~ /name of the prize/_.
   + Knowledge :: Sveriges Riksbank Prize in Economic Sciences in Memory of Alfred Nobel is an award associated with the Nobel prizes
   + Knowledge :: Sveriges Riksbank instituted the Sveriges Riksbank Prize in Economic Sciences in Memory of Alfred Nobel
   + Know-what :: it's a fact
7) The first such prize was awarded in ~1969~ /date of awarding/.
   + Knowledge :: Sveriges Riksbank Prize in Economic Sciences in Memory of Alfred Nobel was awarded for the first time in 1969
   + Know-what :: it's a fact
8) Although it is _~not an official Nobel Prize~ /relationship with Nobel prize/_,its _~announcements and presentations~ /events shared with Nobel prizes/_ are made along with the other prizes.
   + Knowledge :: Sveriges Riksbank Prize in Economic Sciences in Memory of Alfred Nobel is not an official nobel prize
   + Knowledge :: Sveriges Riksbank Prize in Economic Sciences in Memory of Alfred Nobel shares announcements and presentations with nobel prizes
   + Know-what :: it's a fact
9) _~The Royal Swedish Academy of Sciences~ /awarder name/_ awards _the ~Nobel Prize in Physics~, the ~Nobel Prize in Chemistry~, and the ~Nobel Memorial Prize in Economic Sciences~ /names of prizes/_
   + Knowledge :: The Royal Swedish Academy of Sciences awards Nobel Prize in Physics, the Nobel Prize in Chemistry, and the Nobel Memorial Prize in Economic Sciences
   + Know-what :: it's a fact
10) _~The Nobel Assembly at Karolinska Institutet~ /awarder name/_ awards the _~Nobel Prize in Physiology or Medicine~ /name of prize/_.
    + Knowledge :: The Nobel Assembly at Karolinska Institutet awards the Nobel Prize in Physiology or Medicine.
    + Know-what :: it's a fact
11) _~The Swedish Academy~ /awarder name/_ grants the _~Nobel Prize in Literature~ /name of prize/_
    + Knowledge :: The Swedish Academy grants the Nobel Prize in Literature
12) The _~Nobel Peace Prize~ /name of prize/_ is not awarded by a Swedish organization but by the _~Norwegian Nobel Committee~ /awarder/_.
    + Knowledge :: The Nobel Peace Prize is awarded by the Norwegian Nobel Committee
    + Know-what :: it's a fact
13) Each recipient, or laureate, receives a _~gold medal~, a ~diploma~, and a ~sum of money~ /prizes of the award/_ which depends on the _~Nobel Foundation's income~ /factor for the sum of money awarded/ that year_.
    + Knowledge :: the awarded of the nobel prize receives a gold medal, a diploma and a sum of money
    + Knowledge :: the awarded sum of money depends on the Nobel Foundation's income that year
    + Know-what :: it's a fact
14) In _~2011~ /year/_, each prize was worth _~€1.15 million~ /prize value/_.
    + Knowledge :: the value of each nobel prize was €1.15 million in 2011
    + Know-what :: it's a fact

The whole text starting from sentence 9 and ending in sentence 12 may be also seen as a *Know-how* knowledge describing a procedure to decide who should be the awarder for a specific prize.

** 2f and 3f
 1) A _~stock market~ /type of market/_ is a _~public market~ /type of market/_ for the trading of company stock (shares) and derivatives at an agreed price.
    + Knowledge :: stock market is a public market
    + Knowledge :: company stock (shares) and derivatives are traded in a stock market
    + Know-what :: it's a fact
 2) A _~share~ /type of unit/_ is a unit of account for various financial instruments including _~stocks~ /type of financial instrument/_, and investments.
    + Knowledge :: a share is a unit of account used for financial instruments and investments
    + Knowledge :: a stock is a financial instrument
    + Know-what :: it's a fact
 3) On the other hand, a _~derivative~ /type of financial instrument/_ is a financial instrument that has a value, based on the expected future price movements of the asset to which it is linked.
    + Knowledge :: a derivative is a financial instrument
    + Knowledge :: the value of a derivative is based on the expected future price movements of the asset to which it is linked
    + Know-what :: it's a fact

The whole text starting from sentence 2 and ending in sentence 3 may be also seen as a *Know-how* knowledge describing a procedure to distinguish what is a stock and what is a derivative.

** 2g and 3g

 1) Engines can be classified into _~internal~ /type of combustion/_ and _~external~ /type of combustion/ ~combustion~ /type of engine/ engines_.
    + Knowledge :: combustion can be internal or external
    + Knowledge :: combustion engines can be classified on their type of combustion
    + Know-what :: it's a fact
 2) _~Internal combustion engines~ ( ~ICE~ ) /type of engine/_ are engines in which the combustion of a _~fuel~ (substance)_ occurs with an _~oxidizer~ (substance)_ in a _~combustion chamber~ /where combustion happens/_.
    + Knowledge :: in ICE the combustion of fuel (substance) occurs with an oxidizer (substance) in a combustion chamber.
    + Know-what :: it's a fact
 3) On the contrary, in _~external combustion engines~ ( ~ECE~ ) /type of engine/_, such as _~steam engines~_ or _~Stirling engines~ /types of engines/_, the energy is delivered to a _~working fluid~ (substance)_ different of a combustion product.
    + Knowledge :: in ECE the energy is delivered to a working fluid (substance) different of a combustion product
    + Knowledge :: steam engines are ECE
    + Knowledge :: Stirling engines are ECE
    + Know-what :: it's a fact
 4) Working fluids can be _~air~, ~hot water~, or ~pressurized water~ /types of working fluids/_.
    + Knowledge :: air, hot water and pressurized water can be working fluids

The whole text starting from sentence 1 and ending in sentence 4 may be also seen as a *Know-how* knowledge describing a procedure distinguish if an engine is ICE or ECE.

** 2h and 3h
1) _~Chronic disease~ /name of/ treatment_ divides each disease in stages.
   + Knowledge :: chronic diseas treatment divides each disease in stages
   + Know-what :: it's a fact
2) Patients that have _~one~ /number of/ ~chronic disease~ /type of disease/_ are classified in _~one~ /number of/ of these stages_.
   + Knowledge :: a patient having a chronic diseases is classified in a disease's stage
   + Know-what :: it's a fact
3) _~General~ /type of/ practitioners_ base their decisions in the _~current stage of the patient~ and the ~time this patient has been in that stage~ /decision-making factors/_.
   + Knowledge :: a practitioner needs current stage and its duration to make a decision on a patient
   + Know-what :: it's a fact
4) In general, a patient that is in a _~mild-moderate dangerous~ /type of/ stage ( ~MDS~ ) /type of/_ is asked to modify his-her lifestyle ( _~diet, salt intake reduction, moderate exercise~ ) /types of/_, if the patient has been in a MDS for a significant period, he or she is prescribed with _~one~ /number of/ drug_ to _~minimal~ /amount of/ dosage_, while the patient is not improving the dosage is increased with _~fix increments /type of increment/_.
   + Knowledge :: if patient is in MDS stage then ask to change lifestyle
   + Knowledge :: if patient is in MDS stage for a long time then prescribe minimal dose of a drug
   + Knowledge :: if patient is in MDS stage for a long time and he doesn't improve then increase dosage by fix increments
   + Know-how :: it's a procedure describing a sequence of steps dealing with multiple scenarios
5) If a _~maximal~ /amount of/ dosage_ is reached, then a second drug to _~minimal~ /amount of/ dosage_ is prescribed
   + Knowledge :: if dosage is maximal then prescribe second drug at minimal dosage
   + Know-how :: part of the previous procedure
6) Patients can reach treatments with _~4~ /number of/ drugs_
   + Knowledge :: if dosage is maximal then prescribe second drug at minimal dosage
   + Know-how :: can be seen as a part of the previous procedure
   + Know-what :: or as a general fact
7) Patients that arrive in _~highly dangerous~ /type of/ stage ( ~HDS~ ) /type of/_ are directly prescribed with _~one~ /number of/ drug_ and recommended lifestyle changes.
   + Knowledge :: patients in HDS are prescribed a drug and recommended lifestyle changes
   + Know-what :: it's a fact
