#+TITLE: Network Representation

* Limitations of frames

When using frames, we have few pros
- The units of knowledge are self contained
- The knowledge about domain objects (or types) is concentrated all around the objects
However, an frames have an important limitation: they are not designed to establish and exploit semantic relations.

* Definitional networks

Definitional networks focus on the *subtype* or *is-a* relation between concepts. Also
- Inheritance of properties from supertypes to subtypes
- Since definitions are true by definition, the information is often assumed to be necessarily true

With such networks, consistency problems may emerge. Below some examples

#+BEGIN_SRC artist
        ┌──────►Quaker──────────┐
        │                       │
        │                       ▼
Pacifist                      Nixon
        │                       ▲
        │                       │
        └─/──►Republican────────┘
#+END_SRC
Does Nixon inherit pacifism?

#+BEGIN_SRC artist
      ┌────►Elephant───────────┐
      │                        │
      │                        ▼
GrayEntity               RoyalElephant───►Clyde
      │                        ▲
      │                        │
      └─/──►WhiteEntity────────┘
#+END_SRC
Is Clyde gray or white?

* Assertional semantic networks

Assertional semantic networks focus on *assertions*. Unlike definitional networks, the information is assumed to be contingently true (unless explicitly marked with a modal operator).

Some assertional networks have been proposed as models of the conceptual structures underlying natural language semantics.

#+BEGIN_SRC artist
┌────is a Stagirite
│
│         ┌─────is a Macedonian
│         │
│         │
├────teaches
│         │
│         │
│         └─────conquers the world
│
├────is a discipline of───────────────┐
│                                     │
│                                     │
│                            is a philosopher admired by Church Fathers
│                                     │
│                                     │
└────is an opponent of────────────────┘
#+END_SRC
A *relational graph* (Peirce, 1882) for the sentence =A Stagirite teacher of a Macedonian conqueror of the world is a disciple and an opponent of a philosopher admired by Church Fathers=. Relational graphs can only represent $\exists$ and $\wedge$.

Limitations of relational graphs were finally overcome by *existential graphs* (Peirce, 1897), allowing all the logical operators by introducting "ovals" to enclose and negate parts of the graphs.

* Implicational networks

Implication networks use *implication* as the primary relation for connecting nodes. They may be used to represent patterns of beliefs, causality, or inferences.

* Executable networks

Executable networks represent *dynamic processes* or *procedural knowledge*
- Messages are passed through networks arcs
- Procedures can be attached to network nodes-
Examples can be dataflow diagrams and Petri nets

* Other networks

- Learning networks :: Build or extend their representations by acquiring knowledge from examples. The new knowledge may change the old network by adding and deleting nodes and arcs or by modifying numerical values, called weights, associated with the nodes and arcs.
- Hybrid networks :: Combine two or more of the previous techniques, either in a single network or in separate, but closely interacting networks.
* Defining N-ary relations

How can we
- Explicitly describe instances of relations?
- Represent N-ary relations?
- Represent relations involving ordered lists of partecipants?

** New class for a relation

We can create a new class with ~n~ new properties to represent a n-ary relation. Useful when we need to
- Add more attributes to describe a relation
- Show different aspects of the same relation
- Represent n-ary relations having no distinct partecipant

#+BEGIN_QUOTE
Christine has breast tumor with high probability.
#+END_QUOTE

#+BEGIN_SRC artist
                                                                              ┌────────────────────┐
                                                ┌──────diagnosis_value────────►Brest_Tumor_Cristine│
                                                │                             └────────────────────┘
┌───────────┐                      ┌────────────┴─────────┐
│ Christine ├─────has_diagnosis───►│_:Diagnosis_Relation_1│
└───────────┘                      └────────────┬─────────┘
                                                │                             ┌────┐
                                                └──────diagnosis_probability─►│HIGH│
                                                                              └────┘
#+END_SRC

#+BEGIN_QUOTE
Steve has temperature, which is high, but falling.
#+END_QUOTE

#+BEGIN_SRC artist
                                                                ┌────────┐
                                          ┌─temperature_value──►│ELEVATED│
                                          │                     └────────┘
┌─────┐                      ┌────────────┴──────────────┐
│Steve├────has_temperature──►│_:Temperature_Observation_1│
└─────┘                      └────────────┬──────────────┘
                                          │                     ┌───────┐
                                          └─temperature_trend──►│FALLING│
                                                                └───────┘
#+END_SRC

#+BEGIN_QUOTE
John buys a "Lenny the Lion" book from books.example.com for $15 as a birthday gift.
#+END_QUOTE

#+BEGIN_SRC artist
       ┌────┐                                      ┌───┐
       │John◄──has_buyer──┐    ┌──────has_amount───►$15│
       └────┘             │    │                   └───┘
                       ┌──┴────┴──┐
                       │Purchase_1├────────────────────┐
                       └┬────────┬┘                    │
                        │        │                     │
            has_seller──┘    has_object          has_purpose
                │                │                     │
                │                │                     │
┌───────────────▼─┐    ┌─────────▼────┐     ┌──────────▼──┐
│books.example.com│    │Lenny_The_lion│     │Birthday_Gift│
└─────────────────┘    └──────────────┘     └─────────────┘
#+END_SRC
** List as arguments in relation

The idea is to connect arguments via some relations and to relate the one partecipant to this sequence.

#+BEGIN_QUOTE
United Airlines flight 3177 visits the following airports: LAX, DFW, and JFK.
#+END_QUOTE

#+BEGIN_SRC artist
┌───────┐                 ┌─────────┐                    ┌───┐
│UA_1377├─flight_sequence─►UA_1377_1├──────destination───►LAX│
└───────┘                 └────┬────┘                    └───┘
                               │
                           next_segment
                               │
                          ┌────▼────┐                    ┌───┐
                          │UA_1377_2├──────destination───►DFW│
                          └────┬────┘                    └───┘
                               │
                           next_segment
                               │
                          ┌────▼────┐                    ┌───┐
                          │UA_1377_3├──────destination───►JFK│
                          └─────────┘                    └───┘
#+END_SRC
